### ISSUE TITLE
[Gdrive] Cannot edit google-draw in Site Explorer

### ISSUE THREAD

**Issue by thuha** [exo-addons/cloud-drive-extension#45]
Environment: PLF 4.2, Cloud-drive extension 1.3.0-RC1

– Step 1: Go to Documents application --> Personal Documents
– Step 2: Choose "Connect Cloud Documents" action
– Step 3: Choose "Connect your Google Drive" --> Allow Cloud Workspaces app in Google’s “Request for Permission” window --> Connect to Google Drive successfull => Google Drive folder is displayed in Personal Documents drive
– Step 4: Go to Site Explorer --> Personal Documents drive --> Open Google Drive folder --> Select Icon view
– Step 5: Open a Google Drawing file
– Step 6: Choose Edit --> Edit content of Google Drawing file (see WhenEdit.png)
– Step 7: View file by click View button

=> Actual result: The edited content is NOT displayed (see WhenView.png)

=> Expected result: The edited content should be displayed

Note: Other contents (For example: Google Slide, Google Docs, Google Sheet): the edited content is displayed when click View right after editing

(Feedback in issue: https://jira.exoplatform.org/browse/CLDINT-2053)

**Comment by pnedonosko** [comment]
This indeed has a place, happens not always and definitely comes from Google side. Pure images uploaded to Google Drive will not be displayed at all due to CORS restrictions placed by Google. In case of Drawings editor it seems need a time (I observed it as 10-15sec) for complex figures to appear when simple line or arrow appear almost immediately. 
It is not an issue, user (editor) will need to wait for Google internal synchronization for complex drawings.
